language: erlang
branches:
  only:
    - master
    - next
    - pu
    - utp
notifications:
  email: false
  irc:
    - "irc.freenode.org#etorrent"
otp_release:
  - R14B04
  - R14B03
  - R14B02
  - R14B01
