---
- name: build
  type: build-node
  ip: 100.0.10.100
  mem: 2048
  cpu: 2
- name: erlang-n1 
  type: erlang-node
  ip: 100.0.10.101
  mem: 2048
  cpu: 2
- name: erlang-n2
  type: erlang-node
  ip: 100.0.10.102
  mem: 2048
  cpu: 2
- name: erlang-n3
  type: erlang-node
  ip: 100.0.10.103
  mem: 2048
  cpu: 2
- name: erlang-n4
  type: erlang-node
  ip: 100.0.10.104
  mem: 2048
  cpu: 2
